// Code generated by Kitex v0.0.3. DO NOT EDIT.
package serviceb

import (
	"github.com/cloudwego/kitex/server"
	"kitex.service.b/kitex_gen/api"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler api.ServiceB, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
