// Code generated by Kitex v0.0.3. DO NOT EDIT.

package servicea

import (
	"context"
	"github.com/Duslia997/KiteX-A/KiteX-A/kitex_gen/api"
	"github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return serviceAServiceInfo
}

var serviceAServiceInfo = newServiceInfo()

func newServiceInfo() *kitex.ServiceInfo {
	serviceName := "ServiceA"
	handlerType := (*api.ServiceA)(nil)
	methods := map[string]kitex.MethodInfo{
		"serviceA": kitex.NewMethodInfo(serviceAHandler, newServiceAServiceAArgs, newServiceAServiceAResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "api",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.0.3",
		Extra:           extra,
	}
	return svcInfo
}

func serviceAHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.ServiceAServiceAArgs)
	realResult := result.(*api.ServiceAServiceAResult)
	success, err := handler.(api.ServiceA).ServiceA(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newServiceAServiceAArgs() interface{} {
	return api.NewServiceAServiceAArgs()
}

func newServiceAServiceAResult() interface{} {
	return api.NewServiceAServiceAResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ServiceA(ctx context.Context, req *api.Request) (r *api.Response, err error) {
	var _args api.ServiceAServiceAArgs
	_args.Req = req
	var _result api.ServiceAServiceAResult
	if err = p.c.Call(ctx, "serviceA", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
